services:
  CORS\Bundle\VarnishBundle\EventListener\DocumentResponseListener:
    arguments:
      - '@Pimcore\Http\Request\Resolver\DocumentResolver'
      - '@CORS\Bundle\VarnishBundle\ElementHelper'
    tags:
      - { name: kernel.event_subscriber }

  CORS\Bundle\VarnishBundle\EventListener\ElementTagClearerListener:
    arguments:
      - '@Symfony\Component\Messenger\MessageBusInterface'
    tags:
      - { name: kernel.event_subscriber }

  CORS\Bundle\VarnishBundle\EventListener\PathListener:
    tags:
      - { name: kernel.event_subscriber }

  CORS\Bundle\VarnishBundle\ElementHelper:
    arguments:
      - '@fos_http_cache.http.symfony_response_tagger'
      - '@fos_http_cache.cache_manager'

  CORS\Bundle\VarnishBundle\Messenger\InvalidateMessageHandler:
    arguments:
      - '@CORS\Bundle\VarnishBundle\ElementHelper'
    tags:
      - { name: messenger.message_handler }

  CORS\Bundle\VarnishBundle\Controller\AdminController:
    calls:
      - [ setContainer, [ '@service_container' ]]
    tags:
      - { name: controller.service_arguments }